# Use the official Debian 9 image.
# See https://hub.docker.com/_/debian/ for more info.
image: debian:stretch-slim

build:
  stage: build
  before_script: 
    - apt-get update && apt-get -y install phpunit
  script: 
    - cd ./tests
    - ./test.sh
