language: java
sudo: false
dist: trusty
jdk:
- openjdk8
- oraclejdk8
os:
- linux
addons:
  apt:
    packages:
    - libmysql-java
cache:
  directories:
  - "$HOME/.m2"
script:
- echo $VAADIN_CHARTS > ~/vaadin.charts.developer.license
- cd webinterface/
- mvn test
notifications:
  email: false
env:
  global:
    secure: IsTXNpbKMTeMadWfZHbAAY9DOPRyVJ6C0R4djhG8RrPZuhTVT5fMs297sPqf/3wIyUmfoFkZ+jhTPW1VGxPcY8p1edu2G7eg9h1s/C89MvvLe6ngoXwHEzS9DxTIOv4HvYGzQSlloQ3yvVfxvOP5aGGtQ4sGkAhPFcoA5Wmj9Tlg+9Mkrwh5OJ7Cn91qEB43QOAlRs0u9cWYB6Ej8UtGBTrCApE9rPAnFK5qYAjLKxiuq1eoBji4AdR5lOyljjCZF2rkz9YjEHddwjx8bePquRpxdllk6dooUHSkXjK3FcLgJecDejXcjgvAkpv0KdM+KiNwlGjmKWRIJW9nf+U/eXDKClfOwlNGjc96lnRZQzn+4CgSozRjsRyAIGzCdskKFQHoI87d++oNE8z4+UV1n1vQE3yWHsmHJ9lKMTRgY4MW23FrHA+JCWRkPgeVF9JezbtuvdIXEeoTfXT4ceczHSLhYDtdCBqh+OUUzPIJXxIRwmo+JLHZNwlNZ5i7cOLsyyUl0Fpad+wXnUz3Is5r5GSYvScvSUSHtG61VbQf6DXBhnzhQqz7iGHDdXZVeugtOV5eJmOgla4PYFVh22jn6+SEfEQnFti1SqF+S0ogFsfl80o/b+qrnlsA2YmxqKVP2Su1EdX9WvsmK/oGbc2yIwPD4OdUWynDwI+bD+FistM=
