language: java
sudo: false
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
os:
  - linux
addons:
  apt:
    packages:
    - libmysql-java
cache:
  directories:
  - .m2
script:
  - cd webinterface/
  - mvn test
notifications:
  email: false
