name: GitHub CI

on: push

jobs:
  php_8_0:
    runs-on: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Setup PHP with specific version of PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo, pdo_mysql
          tools: phpunit:9.5.10
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"
          ./ci/phplint.sh
          cd ./tests
          ./test.sh

  php_5_6:
    runs-on: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Setup PHP with specific version of PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
          extensions: pdo, pdo_mysql
          tools: phpunit:5.7.27
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"
          ./ci/phplint.sh
          cd ./tests
          ./test.sh
